language: node_js
node_js: 
  - "node"

branches:
  only:
    - master
    - gh-pages

script:
  - git fetch
  - yarn build
  - cp -r build ../
  - git checkout -t origin/gh-pages
  - rm -rf !(.*)
  - cp -r ../build/* ./
  - git add .
  - git commit -m "build by travis"
  - git push