language: node_js
node_js: 
  - "node"

branches:
  only:
    master

script:
  - yarn
  - yarn build
  - cp -r build ../
  - git checkout -b gh-pages
  - rm -rf !(.*)
  - cp -r ../build/* ./
  - git add .
  - git commit -m "build by travis"
  - git push