language: node_js
node_js: 
  - "node"

branches:
  only:
    - master
    - gh-pages

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: ./build/
  on:
    branch: gh-pages
